### ISSUE TITLE
Add support for YoloV5

### ISSUE THREAD

**Issue by snowzach** [snowzach/doods2#10]
https://github.com/ultralytics/yolov5

**Comment by ozett** [comment]
maybe also support from nano to large?
https://github.com/blakeblackshear/frigate/pull/2440#issuecomment-1003310308

**Comment by chrisgilldc** [comment]
Zach
You can grab all the items for the delivery vehicles model [here](https://drive.google.com/file/d/177ZuFfWECC23yp7OHpky1h4fnlrlrBgh/view?usp=sharing).
This includes the Colab notebook (in notebook and straight python format), the model and the source images. You can try the model unless it seems I did it wrong and you want to dive into actual model building itself.
I'm going to look through the latest changes and see if I can run this model now. Thanks.

**Comment by snowzach** [comment]
I actually already got it working using their hub. I am working on arm32 build right now which is always the pain.

**Comment by chrisgilldc** [comment]
Cool, shows what happens when I tend to my day job. :-)
I'll test my model on it when you give the go-ahead

**Comment by snowzach** [comment]
Okay, this is done actually. I gave up on arm though. Pretty much all the packages ended up in a segfault. I may try again someday but for now I'm just not supporting ARM for PyTorch.

**Comment by ozett** [comment]
This is great news!

maybe there should be a illustrating example on the readme.md what great feature this is?
for some downloaded models from the yolo hub?
maybe i can test or provide one in the next days...

**Comment by ozett** [comment]
what image dimension should be confiugrued?
torch-hub says 1280 ??
https://pytorch.org/hub/ultralytics_yolov5/

this correct?
![image](https://user-images.githubusercontent.com/5937811/148747919-23245e12-324f-4837-9de6-0ae263601858.png)

**Comment by ozett** [comment]
look good with 224x224... 
maybe i try 1280x1280 later

![image](https://user-images.githubusercontent.com/5937811/148748095-a989c1ff-cafb-47bc-a912-fa9b40bea107.png)
