### ISSUE TITLE
snowzach/doods2:latest container version not working for rpi aarch64 or armv7l

### ISSUE THREAD

**Issue by Tempura-so** [snowzach/doods2#104]
snowzach/doods2:latest container version not working for rpi (aarch64) or rpi (armv7l)

snowzach/doods2:latest for aarch64

Attaching to doods2
doods2  | INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
doods2  | 2024-04-08 22:06:52,554 - doods.doods - INFO - Registered detector type:tflite name:default
doods2 exited with code 0

snowzach/doods2:1.2.0-aarch64  & snowzach/doods2:1.2.0-armv7l working for both rpi's

snowzach/doods2:1.2.0-aarch64 

Attaching to doods2
doods2  | 2024-04-08 22:08:12,422 - doods.doods - INFO - Registered detector type:tflite name:default
doods2  | 2024-04-08 22:08:15,540 - doods.doods - INFO - Registered detector type:tflite name:mobiledet_320x320_edgetpu
doods2  | 2024-04-08 22:08:15,544 - doods.doods - INFO - Registered detector type:tflite name:cctv1_420x280_edgetpu
doods2  | 2024-04-08 22:08:15,549 - doods.doods - INFO - Registered detector type:tflite name:gray_cctv3_340x340_edgetpu
doods2  | 2024-04-08 22:08:15,555 - doods.doods - INFO - Registered detector type:tflite name:frigate
doods2  | 2024-04-08 22:08:17,767 - doods.doods - INFO - Registered detector type:tensorflow name:tensorflow
doods2  | 2024-04-08 22:08:17,809 - uvicorn.error - INFO - Started server process [1]
doods2  | 2024-04-08 22:08:17,810 - uvicorn.error - INFO - Waiting for application startup.
doods2  | 2024-04-08 22:08:17,810 - uvicorn.error - INFO - Application startup complete.
doods2  | 2024-04-08 22:08:17,811 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)

**Comment by snowzach** [comment]
Not sure I follow... that looks likes it started up

**Comment by Tempura-so** [comment]
Sorry wasn't very clear I could only get doods2 version 1.2.0 to work, the newer versions would not start up with coral usb accelerator

The latest version of doods2 is working, thank you.
