### ISSUE TITLE
Multi-arch docker image

### ISSUE THREAD

**Issue by Curid** [snowzach/doods2#15]
This would allow a single docker-compose file to be used on all architectures.

**Comment by snowzach** [comment]
`:latest` is already multiarch.

**Comment by Curid** [comment]
Huh, has it always been that way? Why have separate tags for each arch?

**Comment by snowzach** [comment]
I have to create different dockerfiles for each one. It's just easier for me to maintain a tag for each arch and then make the multiarch tag from all of those.

**Comment by Curid** [comment]
My bad, it was Frigate that doesn't have it.
