### ISSUE TITLE
[Support:]  Working Example with Node-Red flow?

### ISSUE THREAD

**Issue by ozett** [snowzach/doods2#16]
Has anybody yet a working example to use doods2 with a node-red flow?

**Comment by snowzach** [comment]
All you need is the HTTP Request NODE...

Simple test:
![image](https://user-images.githubusercontent.com/7305473/148227705-d370606c-3b27-4bdd-b57c-05bb6c32e4d3.png)

I am injecting a JSON payload with the config. The data is set to the RTSP URL of my camera (but you could using any http url or provide the base64 encoded image data somehow from upstream)

![image](https://user-images.githubusercontent.com/7305473/148227968-fec2a46f-6cd7-4470-a59b-a7bfaf38472c.png)

Post to the detect endpoint and tell it that it will return a JSON object

![image](https://user-images.githubusercontent.com/7305473/148228088-0f3328b9-65c0-4953-b0f0-ab35463123d9.png)

The HTTP node will spit out the detections:

![image](https://user-images.githubusercontent.com/7305473/148228191-7045370b-78b7-4100-b761-d3216b653752.png)

**Comment by ozett** [comment]
tryin the new bird-object-classifier, 
but somehow doesnt look correct...

my mistake in the jspon-post?, or
maybe probabilty are bird-labels ~ 0.95, https://github.com/snowzach/doods2/issues/3#issuecomment-1006531142)

![image](https://user-images.githubusercontent.com/5937811/148383342-ae683bdd-4d68-4d93-af64-7037eeb4f130.png)

![image](https://user-images.githubusercontent.com/5937811/148383075-9d70bbdb-ca5d-409c-8673-057833edd6e2.png)

flow: 
```

[{"id":"105189b292850818","type":"inject","z":"e4bd61938c7d9524","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{          \"id\": \"whatever\",          \"detector_name\": \"default\",          \"data\": \"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Haussperling_092-2.jpg/300px-Haussperling_092-2.jpg\",     \"image\": \"jpeg\",     \"throttle\": 5,     \"preprocess\": [       \"grayscale\"     ],     \"detect\": {       \"*\": 50,       \"car\": 60     },     \"regions\": [       {\"top\": 0.1, \"left\": 0.1, \"bottom\": 0.9, \"right\": 0.9, \"detect\": {\"*\":50}, \"covers\": false}     ]   }  ","payloadType":"json","x":140,"y":1480,"wires":[["9859f8d8ab598950"]]},{"id":"9859f8d8ab598950","type":"http request","z":"e4bd61938c7d9524","name":"doods2-url","method":"POST","ret":"obj","paytoqs":"ignore","url":"http://192.168.14.34:8080/detect","tls":"","persist":false,"proxy":"","authType":"","senderr":false,"x":310,"y":1480,"wires":[["13719af91de79df7"]]},{"id":"13719af91de79df7","type":"debug","z":"e4bd61938c7d9524","name":"dbg.doods2.response","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":590,"y":1480,"wires":[]}]
```

**Comment by ozett** [comment]
its doing better without preprocess "grayscale" in the json-post.

looks like the classification is not done right,
splitting of the classification-name in two results look wrong...

but looks like the correct birdname
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Haussperling_092-2.jpg/300px-Haussperling_092-2.jpg


![image](https://user-images.githubusercontent.com/5937811/148384588-8f6cd18d-0b5c-47a7-a438-f959516d54c8.png)

**Comment by snowzach** [comment]
Yeah, bug in label processing... pull a new image and try now.

**Comment by ozett** [comment]
yeah, Great. thats the right bird.
i am really happy with this.
thanks a lot for putting that in..

(docker pulled new version quick as light, great!)


i can live with re-calculate the probabilty-value.
maybe the array could be send in a later version with the highes detection-value from first in array?

[0] objectclass1: 99 %
[1] objectclass2: 70%
[2] objectclass3: 3%


![image](https://user-images.githubusercontent.com/5937811/148430755-36fcc005-f338-4df3-809b-f38ed9a9f98c.png)

**Comment by ozett** [comment]
would be great to have the top-scorer as first element in detection-array...

(i got 35 entries with nearly the same score.. would make a new function-node in node-red. to sort them out, didnt it? 
but would be very, very helpful to only take the first element with the highest score )..

![image](https://user-images.githubusercontent.com/5937811/148433377-44478bf2-ad0a-4b59-b52d-c10e46f7e8ce.png)

here my flow, 
still manually: i pull the thumbnail of an event from my bird-cam from frigate and feed it into doods2

```
[{"id":"105189b292850818","type":"inject","z":"e4bd61938c7d9524","name":"","props":[{"p":"id","v":"1641207191.097944-m6lwuv","vt":"str"},{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{    \"id\": \"id\",    \"detector_name\": \"default\",    \"data\": \"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Haussperling_092-2.jpg/300px-Haussperling_092-2.jpg\",    \"image\": \"jpeg\",    \"throttle\": 5,    \"preprocess\": [],    \"detect\": {        \"*\": 50,        \"car\": 60    },    \"regions\": [        {            \"top\": 0.1,            \"left\": 0.1,            \"bottom\": 0.9,            \"right\": 0.9,            \"detect\": {                \"*\": 50            },            \"covers\": false        }    ]}","payloadType":"json","x":310,"y":1580,"wires":[["fde1d6bfda1a52e5","85c0b03ee367ac56"]]},{"id":"fde1d6bfda1a52e5","type":"debug","z":"e4bd61938c7d9524","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":470,"y":1640,"wires":[]},{"id":"85c0b03ee367ac56","type":"change","z":"e4bd61938c7d9524","name":"","rules":[{"t":"set","p":"payload.id","pt":"msg","to":"id","tot":"msg"},{"t":"set","p":"payload.data","pt":"msg","to":"\"http://192.168.14.159:5000/api/events/\" & msg.id & \"/thumbnail.jpg\"","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":520,"y":1580,"wires":[["31587885ec725acc"]]},{"id":"31587885ec725acc","type":"http request","z":"e4bd61938c7d9524","name":"doods2-url","method":"POST","ret":"obj","paytoqs":"ignore","url":"http://192.168.14.34:8080/detect","tls":"","persist":false,"proxy":"","authType":"","senderr":false,"x":710,"y":1580,"wires":[["639f5052fe10732d","9b25e9f4f25dd8b1"]]},{"id":"639f5052fe10732d","type":"debug","z":"e4bd61938c7d9524","name":"dbg.doods2.response","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":930,"y":1580,"wires":[]},{"id":"9b25e9f4f25dd8b1","type":"image","z":"e4bd61938c7d9524","name":"","width":"320","data":"payload.image","dataType":"msg","thumbnail":false,"active":true,"pass":false,"outputs":0,"x":930,"y":1640,"wires":[]}]
```

**Comment by ozett** [comment]
i used some snippets in my experiments (that i dont really understand) to sort the results 
and returned only the two best scores. that worked, but was ugly stiched...

hope you can much better than me.. 😵 

[tf.math.argmax](https://www.tensorflow.org/api_docs/python/tf/math/argmax)
[tf.math.top_k](https://www.tensorflow.org/api_docs/python/tf/math/top_k)

![image](https://user-images.githubusercontent.com/5937811/148434039-6bcf227c-0ed3-42ec-b0bd-637272bc3586.png)

**Comment by ozett** [comment]
cool, cool...
maybe sorting can be done simply in node-red with jsonata...
([found a hint for that](https://discourse.nodered.org/t/payload-array-how-to-sort/29018/6), must experiment...)
![image](https://user-images.githubusercontent.com/5937811/148440082-aac96747-ed88-4d99-8a2b-361e9b8f465b.png)

**Comment by ozett** [comment]
i am overwhelmed (as a no-coding n00b),
whats all possible ... 😵 

![image](https://user-images.githubusercontent.com/5937811/148440566-c884c6d5-a1d8-4c13-b461-e558f240a824.png)



testflow to sort the array simply with one jsonata...
```
[{"id":"105189b292850818","type":"inject","z":"e4bd61938c7d9524","name":"","props":[{"p":"id","v":"1641207191.097944-m6lwuv","vt":"str"},{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{    \"id\": \"id\",    \"detector_name\": \"default\",    \"data\": \"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Haussperling_092-2.jpg/300px-Haussperling_092-2.jpg\",    \"image\": \"jpeg\",    \"throttle\": 5,    \"preprocess\": [],    \"detect\": {        \"*\": 50,        \"car\": 60    },    \"regions\": [        {            \"top\": 0.1,            \"left\": 0.1,            \"bottom\": 0.9,            \"right\": 0.9,            \"detect\": {                \"*\": 50            },            \"covers\": false        }    ]}","payloadType":"json","x":310,"y":1580,"wires":[["fde1d6bfda1a52e5","85c0b03ee367ac56"]]},{"id":"85c0b03ee367ac56","type":"change","z":"e4bd61938c7d9524","name":"","rules":[{"t":"set","p":"payload.id","pt":"msg","to":"id","tot":"msg"},{"t":"set","p":"payload.data","pt":"msg","to":"\"http://192.168.14.159:5000/api/events/\" & msg.id & \"/thumbnail.jpg\"","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":520,"y":1580,"wires":[["31587885ec725acc"]]},{"id":"fde1d6bfda1a52e5","type":"debug","z":"e4bd61938c7d9524","name":"","active":false,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":470,"y":1640,"wires":[]},{"id":"31587885ec725acc","type":"http request","z":"e4bd61938c7d9524","name":"doods2-url","method":"POST","ret":"obj","paytoqs":"ignore","url":"http://192.168.14.34:8080/detect","tls":"","persist":false,"proxy":"","authType":"","senderr":false,"x":710,"y":1580,"wires":[["9b25e9f4f25dd8b1","03702ab20292668c"]]},{"id":"639f5052fe10732d","type":"debug","z":"e4bd61938c7d9524","name":"dbg.doods2.response","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":1140,"y":1580,"wires":[]},{"id":"9b25e9f4f25dd8b1","type":"image","z":"e4bd61938c7d9524","name":"","width":"320","data":"payload.image","dataType":"msg","thumbnail":false,"active":true,"pass":false,"outputs":0,"x":930,"y":1640,"wires":[]},{"id":"03702ab20292668c","type":"change","z":"e4bd61938c7d9524","name":"","rules":[{"t":"set","p":"array","pt":"msg","to":"payload.detections^(>confidence)","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":920,"y":1580,"wires":[["639f5052fe10732d"]]}]
```
