### ISSUE TITLE
Tensorflow1 models support

### ISSUE THREAD

**Issue by eugemaf** [snowzach/doods2#17]
First of all thank you for moving Doods to Python!!
I fully agree with you that Python is a good and well known environment for machine learning and computer vision tasks.

I’m experiencing some problems with a MobilenetV2 model that is actually derived from the model for TF1 provided by [Coral Google](https://raw.githubusercontent.com/google-coral/test_data/master/ssd_mobilenet_v2_coco_quant_postprocess.tflite) and trained with my dataset.

It seems there is a problem in managing the output: the log reports an error on line 90 in tflite.py (omitting the full traceback):
```
2022-01-07 19:03:35,450 - uvicorn.access - INFO - 192.168.1.100:53992 - "POST /detect HTTP/1.1" 500
2022-01-07 19:03:35,450 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
   result = await app(self.scope, self.receive, self.send)
…
…
  File "/opt/doods/detectors/tflite.py", line 90, in detect
    if int(classes[i]) in self.labels:
ValueError: cannot convert float NaN to integer
```
In my opinion this could be related to the fact that my model is TF1 and not TF2, as I can normally manage the output considering the result as tensors, with code similar to this one:
```
def output_tensor(interpreter, i):
  """Returns output tensor view."""
  tensor = interpreter.tensor(interpreter.get_output_details()[i]['index'])()
  return np.squeeze(tensor)

def get_output(interpreter, score_threshold, image_scale=1.0): 
  """Returns list of detected objects."""
  boxes = output_tensor(interpreter, 0)
  class_ids = output_tensor(interpreter, 1)
  scores = output_tensor(interpreter, 2)
  count = int(output_tensor(interpreter, 3))   
  width, height = input_size(interpreter)
  sx, sy = width / image_scale, height / image_scale 
```
while I noted the code in doods2 (tflite.py) is quite different:
```
boxes = self.interpreter.get_tensor(self.output_details[0]['index'])[0] # Bounding box coordinates of detected objects
classes = self.interpreter.get_tensor(self.output_details[1]['index'])[0] # Class index of detected objects
scores = self.interpreter.get_tensor(self.output_details[2]['index'])[0] # Confidence of detected objects
```
May be some change should be done in order to accept also TF1 models in doods.
If this is the case, could you consider to accept also TF1 models in doods2 providing a special flag in configuration (e.g tf_Version: 1 or 2)?
Thanks in advance.

**Comment by snowzach** [comment]
From what I can read, its the exact same code... 

You call basically `np.squeeze(interpreter.tensor(interpreter.get_output_details()[0]['index'])())`
And I am calling `self.interpreter.get_tensor(self.output_details[0]['index'])[0]`

The issue appears to be that there is a NaN in the classes value. It would have gotten past getting the box and the confidence okay at that point. Is your model actually returning a string and not a class number at that point?

**Comment by snowzach** [comment]
Try pulling latest in docker and trying and see if that fixes it.

**Comment by emaffione** [comment]
Unfortunately, it doesn't work. It seems that `classes` is empty...

```
2022-01-08T09:33:22.848984000Z` 2022-01-08 10:33:22,848 - uvicorn.access - INFO - 192.168.1.100:60578 - "POST /detect HTTP/1.1" 500
2022-01-08T09:33:22.850072000Z 2022-01-08 10:33:22,849 - uvicorn.error - ERROR - Exception in ASGI application
2022-01-08T09:33:22.850204000Z Traceback (most recent call last):
....
2022-01-08T09:33:22.851961000Z   File "/opt/doods/api.py", line 28, in detect
2022-01-08T09:33:22.852004000Z     detect_response = self.doods.detect(detect_request)
2022-01-08T09:33:22.852050000Z   File "/opt/doods/doods.py", line 113, in detect
2022-01-08T09:33:22.852095000Z     ret = detector.detect(image)
2022-01-08T09:33:22.852137000Z   File "/opt/doods/detectors/tflite.py", line 92, in detect
2022-01-08T09:33:22.852180000Z     elif int(classes[i]) in self.labels:
2022-01-08T09:33:22.852227000Z ValueError: cannot convert float NaN to integer
```

**Comment by snowzach** [comment]
Do you have code that works with this model? I suspect there is something wrong with it. I noticed you get the number of detections out of the last tensor vs I just loop through the scores. I wonder if that would fix it.

**Comment by snowzach** [comment]
If you want to share the model with me I can tinker with it.

**Comment by emaffione** [comment]
Sure! Pls contact me on eugenio <at> geoinference <dot> com

**Comment by snowzach** [comment]
Okay, try pulling the latest image and trying again.

**Comment by emaffione** [comment]
YES!! It works. I'd like to know where was the problem...

**Comment by snowzach** [comment]
I wasn't quite processing results from Tensorflow Lite properly. It worked on some models but not yours. Now it works on all. Hooray!
