### ISSUE TITLE
[Feature Request]: Choose Detector from Web-Gui 

### ISSUE THREAD

**Issue by ozett** [snowzach/doods2#18]
would love to have a selection-button for to choose one out of all configured detectors 
to test an image with on the web-gui...

![image](https://user-images.githubusercontent.com/5937811/148748871-d235c128-ed14-4be7-abbd-7f258e2221d4.png)

**Comment by ozett** [comment]
i discovered that i can type in the configured detector names in the  upper gui section in the json,
but a button would be very convienient..

**Comment by snowzach** [comment]
Okay, I added a dropdown.
