### ISSUE TITLE
[Support]: Pytorch model not working (birds)

### ISSUE THREAD

**Issue by ozett** [snowzach/doods2#19]
want to use this model:
https://pytorch.org/hub/nicolalandro_ntsnet-cub200_ntsnet/

i configured this new pytorch-feature, but got an error on the gui.
https://github.com/snowzach/doods2/issues/3#issuecomment-1008726340
any advise how to test it better? still not working...

![image](https://user-images.githubusercontent.com/5937811/148751819-dc037267-89e2-4571-9039-3d98ffc18b9a.png)

**Comment by ozett** [comment]
![image](https://user-images.githubusercontent.com/5937811/148752573-9ba18480-39ca-472a-af56-4c0d574d9ed7.png)

**Comment by ozett** [comment]
config: 
![image](https://user-images.githubusercontent.com/5937811/148752662-06d58cb2-d02f-44a1-88e8-15713300ba4b.png)

**Comment by snowzach** [comment]
I am not sure I am going to be able to do much with this model. It's configuration is far to specific to this model. I would basically have to add support for just this model.

**Comment by ozett** [comment]
i have running the first birds-model from tensorflow.
its working fantastic and the 964 bird-classes are mostly correct.

[this py-torch-model](https://pytorch.org/hub/nicolalandro_ntsnet-cub200_ntsnet/) has less bird-classes and only north-america. seems also less precise...

i personally can perfectly live without it.
thanks for looking into it. 

this can go to sleep until someone else on the quest for bird-models lands here in the future ...

**Comment by snowzach** [comment]
I'll just close it for now. Thanks!
