### ISSUE TITLE
MQTT Integration

### ISSUE THREAD

**Issue by Sammy1Am** [snowzach/doods2#20]
This project is exactly what I'm looking for to work on some home automation projects (Frigate is pretty heavy-weight, and I'm not looking for security video recording, just automation based on location, posture, etc.).  The tools I'm using so far often support MQTT as a way to trigger events, so one way or another I'd like to pipe the results out to MQTT.

It wouldn't be too difficult to write a separate service that just connects to the `/stream` WS and forwards all the returned JSON to MQTT, but it would mean a separate service to launch, monitor, etc..  Alternatively, I could try to add some MQTT info to the DetectRequest (sorry if I'm getting some of these names wrong, on a phone so it's hard to tab around) so that DOODS could just optionally send the JSON itself (at the expense of having to include MQTT libraries).

This definitely falls outside the scope of "REST service", so this isn't really a feature request.  I just figured before I fork and start playing around with things I would ask and see if you had any thoughts on which approach would work best since you know the DOODS code.

**Comment by snowzach** [comment]
I actually had the same idea. I've even already install the MQTT module in the container. The container right now is setup to launch in  API mode but I was going to add another option to launch in "MQTT" mode. Essentially it would launch, connect to one or more video streams and MQTT server and just continuously run detections and report what it finds to MQTT if there are matches.

**Comment by Sammy1Am** [comment]
Well that would be _exactly_ what I need (now that I can peruse the code more, I do see the `if args.action == 'api':` line in there).  DOODS has all the configuration I'm really interested from a detection standpoint and any advanced processing would be easier downstream of the MQTT anyway, so having DOODS as a lightweight stream->MQTT component would be ideal.

If I get a chance to try implementing it before you do, I'll make sure to link my code here (though I'm sure whatever you eventually implement will be a little cleaner-- Python's not my strong suit).

I'll probably just copy `@self.api.websocket("/stream")` but read static DetectRequests from the/a config file, and send the json to mqtt instead of the websocket.  Will give me a chance to brush up on Python concurrency too 😉.

**Comment by snowzach** [comment]
Lol Python isn't my strong suit either. This has been good practice.

**Comment by Sammy1Am** [comment]
Alright, great news: I've got it working!
![image](https://user-images.githubusercontent.com/467704/149891606-ea0a3519-8aef-4aa1-a4ca-6dcc89678bfa.png)

Basically there's a new config section that's just a list of requests to be run at startup:
```mqtt:
  requests:
    - id: firstrequest
      detector_name: default
      preprocess: []
      detect:
        "*": 50
      regions:
      - top: 0.1
        left: 0.1
        bottom: 0.9
        right: 0.9
        detect:
          "*": 50
        covers: false
      data: rtsp://url
```

I'll share a commit as soon as it's presentable, but there's still some passwords and such that need to be sanitized (I've only been able to work on this an hour or so some evenings, so it might be a while unfortunately).  Also, I had at least one question (I'm sure I'll have more later):
As you can see in the screenshot, the detection generates multiple MQTT messages per video frame (one per detection result), so they pour in pretty quickly.  I'm sure MQTT is equipped to handle that, but to make things a little less crazy it probably makes sense to do some throttling.  Obviously I can throttle using `throttle` in the DetectRequest, but does that mean something that was detected only briefly might be missed?  E.g. if `throttle: 5`, and something was detectable only for 2 seconds, could it be missed entirely?  If that's the case, would it be useful to add a second throttle on the MQTT publishing instead so that we only mqtt-publish a detection result once every X-seconds but detections can keep running faster?

I feel like there's pros and cons to each approach, but wanted to ask your thoughts.

Excited to clean things up for a minimal commit, but also excited to add a few more features (like passing images in MQTT, and maybe cropping images for each object and using that in the MQTT message).

**Comment by Sammy1Am** [comment]
Phew, sorry that too so long: #24 

Let me know if there's anything that needs adjusting for the PR.  I'll do a better job creating feature branches for the next few things like MQTT images and such)

**Comment by snowzach** [comment]
Thanks a lot! Fantastic work!

**Comment by Sammy1Am** [comment]
Sure; thanks for having code that's pretty easy to understand and modify!  Happy I got it working for myself, but even better that other people can have MQTT support now too :)

**Comment by snowzach** [comment]
This is looking good @Sammy1Am. I changed url to host. Something is wrong running more than one stream though. It seems like one stream hogs all the CPU and never gives it up. I tried changing to threading and it was slightly better but still not really working. Any thoughts? I'm no python expert especially with the async stuff.

**Comment by Sammy1Am** [comment]
Whoops, I guess I should have actually tested with two streams.  I'll take
a look in the next day or two, I'm not a Python expert either, but
generally pretty good with concurrency so I should be able to figure it out.

I was playing around with sending images over MQTT today (which seems to
work great), and realized I should have done a couple MQTT things
differently.  So maybe I'll try to squeeze all those changes (not the
images yet probably) in with a fix.

**Comment by Sammy1Am** [comment]
Hey there, working on this a little now and I was wondering what the background on [this line](https://github.com/Sammy1Am/doods2/blob/44bb07c876ccad2ecf83a15d97a08fa580106548/mqtt.py#L34) was: `time.sleep(0.1)`

It seems like this will throttle the MQTT processing to a max of 10 FPS; if the detectors are working faster than that, wouldn't that cause things to back up and eventually overflow?

**Comment by snowzach** [comment]
So the issue turned out to be that the tensorflow lite detector really just isn't thread safe. I added a mutex into the critical path of the tensorflow lite detector (tensorflow seems time) and it's now balancing the two threads well. I removed the sleep statement as I think it was just coincidence that it managed to not cause a thread collision and made it kind of work with two streams. I will close this issue now. The other thing that could be done is to create a pool of tflite detectors that can be used.

**Comment by snowzach** [comment]
Closing this now as it's working pretty well now.

**Comment by Sammy1Am** [comment]
Ah, cool, that makes sense.  Thanks for the update!

**Comment by snowzach** [comment]
FYI @Sammy1Am the tensorflow lite detector is now multi-thread capable. See the README.md on how to add more threads. (2 is the default)

**Comment by Sammy1Am** [comment]
Oo, awesome!  Thanks for the heads-up!

I installed doods2 on my home server with a Coral board a while back and it worked great for a while and then stopped, but I never got a chance to figure out why.  It's on my list to look into that soon, I'll try out the multithreading too :)
