### ISSUE TITLE
Add more request logging

### ISSUE THREAD

**Issue by snowzach** [snowzach/doods2#25]

**Comment by Mark612** [comment]
Tested and log: detections and also log: all works perfectly, from the Jan 26 2022 code changes. 

For docker, you need to delete your image and re-pull, as a 'recreate' of the image thinks you have the latest version and will not update the code.

Great work!

**Comment by snowzach** [comment]
I am pushing a new image. If there's something I can change in the hass add-on, let me know. Not sure how to force it to pull a new image everytime. I do push new images with the latest tag which is pretty typical.
