### ISSUE TITLE
Doods server causes RPi to freeze

### ISSUE THREAD

**Issue by duffyd** [snowzach/doods2#26]
From time-to-time the Doods server (running in docker) will use up all memory on my RPi, which is also running my hass server, and subsequently freeze the whole machine. Only a reboot will unfreeze it. Any suggestions on how to track memory usage of the Doods server and restart it if it uses up too much memory. Hass logs from the most recent freeze are below:

> Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/image_processing/__init__.py", line 138, in async_update
    await self.async_process_image(image.content)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/image_processing/__init__.py", line 118, in async_process_image
    return await self.hass.async_add_executor_job(self.process_image, image)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/doods/image_processing.py", line 295, in process_image
    response = self._doods.detect(
  File "/srv/homeassistant/lib/python3.8/site-packages/pydoods/__init__.py", line 29, in detect
    response = requests.post(
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /detect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x5eb0b028>: Failed to establish a new connection: [Errno 24] Too many open files'))

**Comment by snowzach** [comment]
So what's likely happening is it's running out of memory and then your system starts to swap (to an sdcard) which effectively kills it. I can try to profile memory usage. Which type are you using (tensorflow or tflite?) I don't have a lot of control over how much memory it's using unless I have a memory leak (which I'm not sure how that's possible in Python but I'm no python expert) Let me know what model you're using and I can try it here and see if it leaks memory or something.

**Comment by duffyd** [comment]
Thanks for getting back to me. I'm using the default tflite detector model.

**Comment by snowzach** [comment]
Someone made a PR that might have fixed the issue if you want to try again. Be sure to pull the latest image. I actually just added prometheus metrics as well if you `GET /metrics` and it includes memory information. 
```
GET /metrics
process_virtual_memory_bytes 5.366218752e+09
process_resident_memory_bytes 5.36748032e+08
```
It just occurred to me that you can limit memory usage of a docker container. I'm not how you're running it.. (with hass supervisor or just in docker) but if you're just running it in docker you could limit the memory usage with `-m 1g` or something equivalent in whatever hypervisor you're using. 

A quick scan of the hassio docs, it doesn't look like you can set limits there sadly. Hopefully you're using another method.

**Comment by snowzach** [comment]
I really wonder if I had an issue with thread collisions on tensorflow lite. I made another change that might fix this as well.

**Comment by snowzach** [comment]
Gonna close for now. Reopen if still an issue

**Comment by duffyd** [comment]
Hello again @snowzach, apologies about the delay in getting back to you. I pulled the updated docker image and restarted the docker image and the server froze up again a couple of days ago and I had to do a hard restart. When it's in that state it doesn't respond at all so trying to do a **GET /metrics** wouldn't work either. As my RPi just has 1gb of memory and I'm also running HA on it, what would be the minimum memory you'd recommend I run doods2 with?

One other thing, according to Google I can't re-open my own issues if a repo collaborator closed them.

**Comment by snowzach** [comment]
Are you using the default config? The only thing I can suggest is edit the config to only use tensorflow light. 1gb isn't much.

**Comment by duffyd** [comment]
This is my config:

> image_processing: 
  - platform: doods 
    url: "http://127.0.0.1:8080" 
    detector: default  
    confidence: 70 
    source: 
      - entity_id: camera.hall_entry  
    file_out: 
      - "/home/homeassistant/cameras/{{ camera_entity.split('.')[1] }}_latest.jpg" 
      - "/home/homeassistant/cameras/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg" 
    labels: 
      - person

**Comment by snowzach** [comment]
I just realized the error is too many open flies... Something is using file handles and not closing them. It could be doods... 
Can you run this next time you experience the error: https://askubuntu.com/questions/181215/too-many-open-files-how-to-find-the-culprit

**Comment by duffyd** [comment]
Ok, can do

**Comment by duffyd** [comment]
Ok, HA just died again and I ran the following:

> lsof +c 0 | awk '{ print $2 " " $1; }' | sort -rn | uniq -c | sort -rn | head -20

Top row returned was:

> 1880 9881 python3

This is the doods process

**Comment by snowzach** [comment]
1880 isn't a small number of files/handles, but it's pretty far from a large number too though... Was the error definitely too many open files?

**Comment by duffyd** [comment]
Could you please give me some further direction re. how to check the error log on the doods server? As I'm seeing a doods related error at 10am this morning on the home assistant end but the doods server has restarted since then (probably due to the *-m* setting I've got on the docker container) so I'm unsure how to go back through the earlier logs.

**Comment by duffyd** [comment]
Just an update that my RPi was becoming very unresponsive again. Specifically the memory usage was peaking but when I did the **lsof** command above it showed the following, i.e. home assistant had most file handles open and doods was second:

```
  28329 538 hass
   1880 20985 python3
```

Despite this, I thought it was still related to doods so I shutdown the docker container running doods and my system came back to being responsive again.

**Comment by snowzach** [comment]
That's almost certainly memory related. I really don't have control over how much memory the tensorflow libraries use. I will check again for leaks but basically it uses more memory until it has to use swap. You can't really use an SDCARD for swap because it's too slow. The Pi basically stops responding until you shutdown DOODS and free up memory.

**Comment by duffyd** [comment]
Just got this in home assistant.

```
2022-03-04 15:05:45 ERROR (MainThread) [homeassistant] Error doing job: socket.accept() out of system resource
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 164, in _accept_connection
    conn, addr = sock.accept()
  File "/usr/lib/python3.8/socket.py", line 292, in accept
    fd, addr = self._accept()
OSError: [Errno 24] Too many open files
```

**Comment by duffyd** [comment]
Just FYI I've decided to not run doods on my RPi due to your comments re. memory swapping using an SD card so you may as well close this issue now. Thanks.

**Comment by snowzach** [comment]
That's actually a leak in homeassistant from the looks of it.

**Comment by snowzach** [comment]
Sure.. give a hollar if it pops up again. I do think there's a resource leak in DOODS somewhere that I'm trying to track down but it appears to be related to memory and not file handles.
