### ISSUE TITLE
[FR]: Openlogo-model: logo-detection with pytorch

### ISSUE THREAD

**Issue by ozett** [snowzach/doods2#28]
maybe this is a pytorch model like yolo5 and can be integrated?
is not on the torch-hub. so this must be done manually?

Modell:
https://github.com/OlafenwaMoses/DeepStack_OpenLogo/releases/download/v1/openlogo.pt

Site:
https://github.com/OlafenwaMoses/DeepStack_OpenLogo

![image](https://user-images.githubusercontent.com/5937811/151658606-9d20ad0b-3dc6-463f-b58b-497ab585861b.png)

**Comment by ozett** [comment]
looks like it could be done like yolov5

![image](https://user-images.githubusercontent.com/5937811/151658688-c8b6ddf0-44aa-47c1-890c-5748c0512a54.png)

**Comment by snowzach** [comment]
Yeah, Deepstack looks to be a lot of helper stuff around the yolo models. I was able to add support for it. I added a new model type of deepstack. You can download the .pt model and set type: deepstack and modelFile: models/openlogo.pt

**Comment by ozett** [comment]
whats this?

```doods.doods - ERROR - Could not create detector deepstack/logo: PytorchStreamReader failed reading zip archive: failed finding central directory
```
![image](https://user-images.githubusercontent.com/5937811/152635629-cc4d750b-c200-4584-848b-2e7ca37f7983.png)

config.yaml (unsure what image-size needed for openlogo.pt...)
```
    - name: logo
      type: deepstack
      modelFile: models/openlogo.pt
      width: 224
      height: 224
      numThreads: 0
      numConcurrent: 4


```

**Comment by ozett** [comment]
my model file was incomplete from a broken download.
downloaded it again. and looks better.
can you cache the downloaded models (like yolov5 des), so they are not re-downloaded every start?

![image](https://user-images.githubusercontent.com/5937811/152635746-a408ce35-9eed-414b-887e-3bfc8b58e236.png)

**Comment by ozett** [comment]
image size error?
what size did you use for testing?

![image](https://user-images.githubusercontent.com/5937811/152635819-75429116-60e8-4c26-b9b9-5f76f7638ffa.png)

**Comment by ozett** [comment]
yolov5 works fine:
![image](https://user-images.githubusercontent.com/5937811/152635920-9db9c33c-eca2-4262-9479-bb233cd04692.png)

**Comment by ozett** [comment]
whats this error?

![image](https://user-images.githubusercontent.com/5937811/152636056-9a20ad74-cb25-44cd-a54e-a6d81a1b2c83.png)

**Comment by ozett** [comment]
as openlogo.pt worked in my test like a yolo model, may i have to configure it in dood2.yaml
simply as yolov5?

**Comment by ozett** [comment]
openlogo still throws error:

![image](https://user-images.githubusercontent.com/5937811/159113823-f576bd1b-3ec5-44c8-af07-315476a04116.png)

config:
```
   - name: logodeep
      type: deepstack
      modelFile: models/openlogo.pt
      width: 640
      height: 640
      numThreads: 0
      numConcurrent: 4
```

**Comment by snowzach** [comment]
I don't totally understand the deepstack framework but at a glance it definitely looks like it's related. It looks like something changed from Yolov6. I will try to figure out how to make it use a yolo5 model. I am buried at the moment, not sure how soon I can get to it though.

**Comment by snowzach** [comment]
I think this might be a different issue. Openlogo works fine for me.

**Comment by ozett** [comment]
what causes my error? i tested only with one image. maybe that image?
i will check

**Comment by snowzach** [comment]
Yeah, any image that fails will help me.

**Comment by ozett** [comment]
https://github.com/snowzach/doods2/issues/38#issuecomment-1073282096

**Comment by snowzach** [comment]
Okay, closing this ticket again in favor of the other one
