### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by valentinfrlch** [snowzach/doods2#31]
I just switched from DOODS to DOODS2. When I try to start the container I get the following error:

```
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xf7dc4310 (most recent call first):
<no Python frame>
```

I am running doods2 on a raspberry pi 4. In my understanding containers always run with root privileges. Nevertheless I tried running "sudo docker run ...", still without success.

Does anyone know how to solve this issue?

**Comment by snowzach** [comment]
Pretty sure this is the issue https://docs.linuxserver.io/faq

**Comment by valentinfrlch** [comment]
Thanks a lot! upgrading libseccomp2 did the trick.
