### ISSUE TITLE
[FR:] Facedetection models possible?

### ISSUE THREAD

**Issue by ozett** [snowzach/doods2#34]
fiddling with deepstack i came to the idea that doods2 could have face-models.
i see deepstack make use of ARCface and  MobileFaceNet

https://github.com/johnolafenwa/DeepStack/blob/5da0520b855b8db0692c639a1d4d8c83a49e9883/intelligencelayer/shared/recognition/networks.py#L77-L78

https://github.com/johnolafenwa/DeepStack/blob/5da0520b855b8db0692c639a1d4d8c83a49e9883/intelligencelayer/shared/recognition/networks.py#L224

but i dont see how this could be implemented in doods2

**Comment by ozett** [comment]
could that work?
https://github.com/timesler/facenet-pytorch

**Comment by ozett** [comment]
or this?
https://github.com/deepinsight/insightface?ref=https://githubhelp.com

**Comment by ozett** [comment]
i found deepstack in your code...
https://github.com/snowzach/doods2/blob/9dcda621cec9c1ddb487737383194f0c02dcde99/detectors/deepstack.py#L13

maybe facedetection from deepstack could be made usable?

https://github.com/johnolafenwa/DeepStack/blob/5da0520b855b8db0692c639a1d4d8c83a49e9883/intelligencelayer/shared/face.py#L26

**Comment by dbeckers99** [comment]
I'm on the same way. I think using a different tensorflow model should be easy to implement.

My main problem is: I want to train the existing tensorflow model with false positive person detection images to make the detection result more reliable. But training Tensorflow models isn't that easy, you have to learn a lot about.

Anyone has an easy walkthrough to share?

**Comment by snowzach** [comment]
I wish there was on.. sorry.. Gonna close this to clean up issues for now.
