### ISSUE TITLE
does not create multiple images

### ISSUE THREAD

**Issue by fokcuk** [snowzach/doods2#35]
I am trying to detect cats trespassing but for some reason, it is not saving the history of images, just the latest one.
This is what I am using for config. It used so save extra images too, but it stopped doing it for the last 2 days (plenty of space on disk)
`  - platform: doods
    url: "http://192.168.1.112:8080"
    detector: default
    source:
      - entity_id: camera.garage_camera
    file_out:
      - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/config/www/doods/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    confidence: 20
    scan_interval: 1
    area:
      covers: false
    labels:
      - name: person
        confidence: 55
      - name: car
        confidence: 50
      - name: bird
        confidence: 50
      - name: cat
        confidence: 20
      - name: dog
        confidence: 20`

**Comment by snowzach** [comment]
Not sure... works for me... does the directory /config/www/doods exist? is it writable by the homeassistant user?

This is my template: `    - "/data/images/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"`

**Comment by fokcuk** [comment]
Yeah, I still had images in it from about 2 days ago. But nothing new. I know files are created as I see a recent image from today. Just strange that it stopped saving other files.

**Comment by snowzach** [comment]
My guess is a permissions issue. Nothing has changed from DOODS or the add-on.

**Comment by snowzach** [comment]
You could open a ticket on home assistant maybe... They manage the doods code there, I haven't made any changes to DOODS itself.
