### ISSUE TITLE
Websockets memory leak

### ISSUE THREAD

**Issue by Curid** [snowzach/doods2#37]
It's slowly using more and more memory. It takes a few million requests before it's noticeable. 
Anything I should do before restarting it?

**Comment by snowzach** [comment]
I just pushed an image with tracing. Set environment variable `SERVER_TRACE=true` and then you cat `GET /memory` and it should return a top memory allocations. Hopefully something will show up there.

**Comment by Curid** [comment]
Thanks for the quick response!

Fresh start.
```
"traced memory: 2084 KiB  peak: 4362 KiB  overhead: 1041 KiB",
"abc.py:102: size=61.3 KiB, count=770, average=82 B",
```

After 1 day.
```
"traced memory: 20124 KiB  peak: 20370 KiB  overhead: 14143 KiB",
"abc.py:102: size=119 KiB, count=1218, average=100 B",
"asyncio/base_events.py:397: size=5120 KiB, count=5, average=1024 KiB",
"threading.py:908: size=7276 KiB, count=206951, average=36 B",
"threading.py:913: size=4096 KiB, count=1, average=4096 KiB",
"/opt/doods/doods.py:124: size=339 KiB, count=5, average=67.8 KiB",
"/opt/doods/detectors/tflite.py:58: size=339 KiB, count=2, average=169 KiB",
"<string>:1: size=140 KiB, count=1994, average=72 B",
"tracemalloc.py:65: size=124 KiB, count=1990, average=64 B",
"base64.py:87: size=106 KiB, count=1, average=106 KiB",
"email/utils.py:118: size=81.2 KiB, count=800, average=104 B"
```

**Comment by Curid** [comment]
Day 1 vs Day 2.
```
"traced memory: 20124 KiB  peak: 20370 KiB  overhead: 14143 KiB",
"traced memory: 30525 KiB  peak: 31081 KiB  overhead: 26091 KiB",

"threading.py:908: size=7276 KiB, count=206951, average=36 B",
"threading.py:908: size=13.4 MiB, count=389757, average=36 B",

"threading.py:913: size=4096 KiB, count=1, average=4096 KiB",
"threading.py:913: size=8192 KiB, count=1, average=8192 KiB",

"email/utils.py:118: size=81.2 KiB, count=800, average=104 B",
"email/utils.py:118: size=115 KiB, count=1128, average=104 B",
```

**Comment by snowzach** [comment]
Does the threading continue to grow by 7MB every day?

**Comment by Curid** [comment]
> Does the threading continue to grow by 7MB every day?

Yes.

> Are you maintaining a websocket connection for days on end?

Yes. All requests are done through a single connection. I did restart it once or twice in the last few days.

Closing the connection doesn't help.
`uvicorn.error - INFO - connection closed`

Day 2 vs Day 4.
```
"traced memory: 30525 KiB  peak: 31081 KiB  overhead: 26091 KiB",
"traced memory: 49901 KiB  peak: 54556 KiB  overhead: 48872 KiB",

"threading.py:908: size=13.4 MiB, count=389757, average=36 B",
"threading.py:908: size=25.0 MiB, count=728712, average=36 B",

"threading.py:913: size=8192 KiB, count=1, average=8192 KiB",
"threading.py:913: size=16.0 MiB, count=1, average=16.0 MiB",

"email/utils.py:118: size=115 KiB, count=1128, average=104 B",
"email/utils.py:118: size=168 KiB, count=1654, average=104 B",
```

**Comment by snowzach** [comment]
Well, it's apparently leaking threads somewhere as near as I can tell. I can try to keep digging.

**Comment by Curid** [comment]
Any progress? I can give it a try.

**Comment by snowzach** [comment]
I did some digging with threading on Python, it kind of turns into a Black Box where I can't see what the actual issue it. I did try to make sure all threads are exiting and it seems okay. My current guess is that some of the detections just go off into lala land and never return and thus it starts building up dead threads. I guess I need to see if I can figure out how to track threads that maybe have died and try to reap them at some point. I'm just not a python expert so It's going to take me a bit. Any help would be greatly appreciated if you know Python.

**Comment by snowzach** [comment]
Which websocket endpoint are you using? `/stream` or `/detect`

**Comment by snowzach** [comment]
@Curid give the new image a shot. I tried to handle timeouts with detections. Hoping this clears it up. Still would like to know what endpoint you are using.

**Comment by Curid** [comment]
I'm using `/detect` 
Are you able to reproduce the issue? I think every detection is successful.

**Comment by snowzach** [comment]
I don't have a good way to set it up and let it run forever. I haven't reproduced it. But I have found some issues that I made some changes to fix. Are you able to test again?

**Comment by snowzach** [comment]
If you are using Tensorflow lite, it's not thread safe as of now. If you are using this enough I could try to enable threading for it. All the others are thread safe as far as I can tell.

What do you mean you ran it for 1m requests with inference disabled?

**Comment by Curid** [comment]
Turns out it's only reproducible inside the container...

The following scripts reproduces the issue 100% of the time for me. 

<details>
<summary>api.py</summary>

```
# Only leaks inside container. Leak is noticeable after about 200 requests.
import uvicorn
import logging
import asyncio
import threading
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from pydantic.dataclasses import dataclass
from dataclasses import asdict
import tracemalloc

@dataclass
class DetectRequest:
    id: str


@dataclass
class DetectResponse:
    def asdict(self, include_none=True):
        ret = asdict(self)
        return ret


class API():
    def __init__(self):
        self.api = FastAPI()
        # Borrow the uvicorn logger because it's pretty.
        self.logger = logging.getLogger("doods.api")

        tracemalloc.start()
        
        def mock_detector():
            return DetectResponse()

        @self.api.websocket("/detect")
        async def detect_stream(websocket: WebSocket):
            await websocket.accept()
            detect_responses = asyncio.Queue()

            async def detect_handle(detect_request: DetectRequest):
                loop = asyncio.get_event_loop()
                fut = loop.run_in_executor(None, mock_detector)
                try:
                    detect_response = await asyncio.wait_for(fut, 300) # Kill it and exit after 5 minutes
                    await detect_responses.put(detect_response)
                except asyncio.TimeoutError:
                    self.logger.error("Detector timeout error")
                except Exception as e:
                    self.logger.error("Exception({0}):{1!r}".format(type(e).__name__, e.args))

            def detect_thread(loop, detect_request: DetectRequest):
                try:
                    asyncio.set_event_loop(loop)
                    loop.run_until_complete(detect_handle(detect_request))
                    loop.close()
                except Exception as e:
                    self.logger.error("Exception({0}):{1!r}".format(type(e).__name__, e.args))
                    loop.close()

            async def send_detect_responses():
                try:
                    while True:
                        detect_response = await detect_responses.get()
                        await websocket.send_json(detect_response.asdict(include_none=False))
                except Exception as e:
                    self.logger.error("Exception({0}):{1!r}".format(type(e).__name__, e.args))

            send_detect_responses_task = asyncio.create_task(send_detect_responses())
            
            while True:
                try:
                    detect_config = await websocket.receive_json()
                    detect_request = DetectRequest(**detect_config)
                    loop = asyncio.new_event_loop()
                    threading.Thread(target=detect_thread, args=(loop, detect_request,)).start()
                except WebSocketDisconnect:
                    send_detect_responses_task.cancel()
                    break
                except Exception as e:
                    self.logger.error("Exception({0}):{1!r}".format(type(e).__name__, e.args))
                    send_detect_responses_task.cancel()
                    break

        @self.api.get("/memory")
        async def memory():
            current_mem, peak_mem = tracemalloc.get_traced_memory()
            overhead = tracemalloc.get_tracemalloc_memory()
            ret = [ "traced memory: %d KiB  peak: %d KiB  overhead: %d KiB" % (
                int(current_mem // 1024), int(peak_mem // 1024), int(overhead // 1024)
            ) ]
            snapshot = tracemalloc.take_snapshot()
            stats = snapshot.statistics('lineno')            
            for trace in stats[:20]:
                ret.append("%s" % (trace))

            data = {}
            data['traceback'] = ret
            return data

        uvicorn.run(self.api, host="0.0.0.0", port=8080) 


if __name__ == "__main__":
    API()
```

</details>

<details>
<summary>client.py</summary>

```
import asyncio
import websockets

async def main():
    async with websockets.connect("ws://127.0.0.1:8080/detect") as ws:
        i = 0
        while True:
            i += 1
            print(i)
            await ws.send('{"id":"x"}')
            await ws.recv()

if __name__ == "__main__":
    asyncio.run(main())

```

</details>

`docker run -it --entrypoint bash -v $(pwd):/opt/doods -p 8080:8080 snowzach/doods2:latest`

**Comment by snowzach** [comment]
Yeah, it's something to do with threading... I just gotta figure out why it's not cleaning them up.

**Comment by snowzach** [comment]
Are you saying if you install tensorflow or whatever on your local machine and then run this it works without a leak?

**Comment by snowzach** [comment]
Your example isn't really reproducing it from what I can see... It looks like a leak but it's continuously generating threads that hang around for 5 minutes. It should look to stabilize after around 5 minutes. You're going to have a gazillion threads running which looks like it's leaking. However, I do think that helped me figure out what's going on... I came across this: https://bugs.python.org/issue39074

**Comment by snowzach** [comment]
Yeah, that's 100% the issue... I'll see what I can figure out...

**Comment by snowzach** [comment]
So it's interesting, it appears the python has the fix for the issue but it still leaks when join isn't specified. I'll have to think of something else.

**Comment by snowzach** [comment]
Okay, I switched to using the Python ThreadPoolExecutor instead of making threads. It appears to be cleaning up after itself. Give that a shot and let me know.

**Comment by Curid** [comment]
> Are you saying if you install tensorflow or whatever on your local machine and then run this it works without a leak?

Yes, that's why it was so hard to reproduce. It works fine locally with `Python 2.7.16` and `Python 3.7.3`

Have you considered basing the docker image on `python:alpine3.15`? 
If you build the dependencies from source you can use a single Dockerfile for all platforms. It would also make the image much smaller.

**Comment by snowzach** [comment]
Building tensorflow is an absolute nightmare. I really doubt it would compile on alpine. I would love to use one Dockerfile. It took me probably a month just to get a docker image that worked on all the platforms I wanted to support. It took me even longer on Doods1 because it was in Go. 

Did you get a chance to try the new image? I'm pretty sure the image is fixed.

**Comment by Curid** [comment]
Seems to be fixed. No leak after 1 day.

> Building tensorflow is an absolute nightmare.

Can confirm, took me a week last time I did it.

**Comment by snowzach** [comment]
Woot!
