### ISSUE TITLE
[FR:] Make confidence-number configurable on returning Image

### ISSUE THREAD

**Issue by ozett** [snowzach/doods2#39]
would like to format the Precentage that is printed on the detection image.
i dont see global options for this
i dont see local detector options for this.

for my needs i would prefer two digits, like 90% or 62% 
not 90.xxxxxxxxxxxxxxx.

would be best it could be configured per DETECTOR, not globally...

for example to much digits here:
![image](https://user-images.githubusercontent.com/5937811/159720496-6f608de1-1f84-42c8-80c6-74e0625ac71d.png)

**Comment by snowzach** [comment]
Okay, the image annotations now only show whole numbers. The JSON results will still return the floating point numbers.

**Comment by ozett** [comment]
no change on this behaviour ?  do you let this be the default? 

love to see an [option on the rest-api](https://github.com/snowzach/doods2#detect-request)?

your comment not fully explains to me your opinion on this ... 🤔 
or should i pull?
