### ISSUE TITLE
Installing doods2 using python virtual environment

### ISSUE THREAD

**Issue by dawiinci** [snowzach/doods2#43]
Since docker isn’t supported well on macOS I would prefer an installation in a python venv. Can this be done and if so, is there a guide available?

**Comment by snowzach** [comment]
The hard part will be getting tensorflow installed. There is an arm64 docker image. I haven't personally tried it but might work well. I don't have a guide. Getting tensorflow to work is a pain.

**Comment by dawiinci** [comment]
This should be the easy part:
https://www.tensorflow.org/install/pip

**Comment by snowzach** [comment]
Did you ever try the aarch64 docker image? There's a requirements and you can try it. Tensorflow usually requires a lot of C compiliation.
