### ISSUE TITLE
Running doods2 on a Jetson Nano 4GB

### ISSUE THREAD

**Issue by Idefix0496** [snowzach/doods2#45]
Hi,
did anyone manage to run doods2 on a Jetson Nano 4GB Board including GPU support ? I found some related Issues in the old doods repository containing an old Dockerfile. Are there any plans to natively support it?

Thanks

**Comment by snowzach** [comment]
I started to look into it but ended up with a Jetson that was wayyyy too old to support it. The Nano's are a bit out of my range at the moment. lol if you have a spare lying around to donate to the cause I could look into... I know its not probably something people have a few lying around though.

**Comment by joenet-86** [comment]
I am also looking for a solution to get the benefit of the Nvidia GPU support. A one-box computer like the Jetson family would be perfect. Do you have any recommendation for a suitable hardware?

**Comment by Idefix0496** [comment]
Hey, thanks for the replies. So I've got a Jetson Nano 4GB with the B01 Board Revision. Is that new enough ?
If you got something like a Dockerfile which I can run to build Doods on the Nano, I'm more than happy to give it a shot.
The final goal for me would be running a YOLOV5 Modell on the Nvidia Maxwell GPU of the Nano via Doods2. 
The Perfomance of the let's say yolov5l should be around 1-1.5 FPS on the Nano. Which is a lot better than running it on any suitable CPU I got and exactly what I need.

@joenet-86
The thing is there are really not any other alternatives I'm aware of in that Performance and TDP Range.
I have no Idea what discrete GPU I shold use to get the same Level of performance and Power. If even possible.
So if someone has any recommendation for a suitable discrete GPU I'm interested too.

**Comment by snowzach** [comment]
The arm64 build should work on the nano. If you try just running it in docker on the nano and it works, you would just need to find a tensorflow base image with the nvidia drivers I would think. I doubt anything else would work that fast with any decent power draw.
