### ISSUE TITLE
Nvidia GPU support with Intel CPU 

### ISSUE THREAD

**Issue by joenet-86** [snowzach/doods2#47]
Hello,
I am not experienced with the differences of the various docker images, however, I could get a workstation with a Nvidia Quadro K420 and an Intel Core i7 CPU.
Could I use the amd64-gpu image with this hardware to get the GPU support or is it limited to amd CPUs?
Thanks for your support in advance.

**Comment by snowzach** [comment]
Yes it will work fine.

**Comment by joenet-86** [comment]
Great. Thanks for the confirmation.
