### ISSUE TITLE
yolov5s doesn't appear to be present

### ISSUE THREAD

**Issue by codicusmaximus** [snowzach/doods2#56]
The documentation on the github readme says that yolov5s should be one of the built in models available, but the /detectors page doesn't list it as available.

I only see two detectors available -- "name":"default"  and "name":"tensorflow"

**Comment by snowzach** [comment]
It's actually called `pytorch` what error does it show in the logs? It will need to download the model from the internet.

**Comment by snowzach** [comment]
Repull your image and try it now..

**Comment by snowzach** [comment]
If you are running it on a Raspberry Pi, it won't have Pytorch. It's way too slow to be useful. Reopen if issues.
