### ISSUE TITLE
Object has no attribute 'input_data'

### ISSUE THREAD

**Issue by Curid** [snowzach/doods2#57]
This is from a png image sent over WebSockets. I think the image is being sent, maybe there's a issue decoding it? Could you add some error handling?

`doods.api - ERROR - Exception(AttributeError):("'TensorflowLite' object has no attribute 'input_data'",)`

**Comment by snowzach** [comment]
That generally means the model you are using doesn't have the right attributes. Are you using a different model?

**Comment by Curid** [comment]
Turns out my model was broken..

**Comment by hkrob** [comment]
> Turns out my model was broken..

How did you fix it?
My model is working in my testing (Jupyter notebook) but everytime I try to load it in DOODS2 I get 
```AttributeError: 'TensorflowLite' object has no attribute 'input_data'```

I've tried using 2.7.0 and 2.14 tensorflow .... any ideas?!

**Comment by hkrob** [comment]
> I think I got the error from using a model that wasn't quantized. I suggest comparing the input format of your model with a working model.
> 
> ```python
> import tensorflow as tf
> 
> model_path = "./model.tflite"
> interpreter = tf.lite.Interpreter(model_path=model_path)
> 
> input_details = interpreter.get_input_details()
> output_details = interpreter.get_output_details()
> 
> print(input_details)
> print(output_details)
> ```

Thanks for that, tried but still the same... I think I've run out of ideas!

```
Model has been saved and quantized.
Input details: [{'name': 'serving_default_conv2d_input:0', 'index': 0, 'shape': array([  1, 128, 128,   3], dtype=int32), 'shape_signature': array([ -1, 128, 128,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
Output details: [{'name': 'StatefulPartitionedCall:0', 'index': 21, 'shape': array([1, 1], dtype=int32), 'shape_signature': array([-1,  1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
```

Frigate:

```ValueError: Cannot set tensor: Got value of type UINT8 but expected type FLOAT32 for input 0, name: serving_default_conv2d_input:0```

**Comment by Curid** [comment]
> 'shape': array([  1, 128, 128,   3],   'dtype': <class 'numpy.float32'>,

You have to patch doods to convert the input image to this format. The output seems to only be a single number, which doesn't make sense for an object detection model.

**Comment by hkrob** [comment]
Could that be because it's a binary selection?
My model is simply open or closed, classification not detection..
I don't think I can patch doors but I could potentially change to a
detection vs classification approach....

**Comment by snowzach** [comment]
It would be nice to change it to support that sort of model by detecting the outputs. I'm buried.. I may try to look someday  or happy to accept PRs

**Comment by hkrob** [comment]
Sounds good, do you have any instructions on building a model that would
work?

**Comment by snowzach** [comment]
I do not... sorry... I've never actually trained a model..
