### ISSUE TITLE
Docker image version

### ISSUE THREAD

**Issue by lettore** [snowzach/doods2#59]
I suggest to use a version when you build Docker Images instead of build only a latest tag. This is because if something is broken in the last build there's no way to return to the old working image as there's only a tag available.

**Comment by snowzach** [comment]
Yeah, I should... I'll start adding that.

**Comment by snowzach** [comment]
If you're referring to this error: doods.doods - ERROR - Could not create detector pytorch/pytorch: No module named 'IPython' it's because the pytorch people changed something. A rollback in version wouldn't have fixed it..

**Comment by lettore** [comment]
No it's just about good docker manners.
