### ISSUE TITLE
Crashes on Raspbian 10

### ISSUE THREAD

**Issue by tomasrudh** [snowzach/doods2#6]
Thanks for all your work!

I am running Doods on a Raspberry Pi 4B, running Raspbian 10, without problem. However, Doods2 crashes just after start, saying:
```
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted
```

If I start the container with this command it works:
`docker --privileged run -it -p 8080:8080 snowzach/doods2:latest`

So, just to let anyone else know, having that problem.

**Comment by snowzach** [comment]
Yeah, this is a bug in Raspbian+Docker... You need to upgrade a library. This should fix it: https://docs.linuxserver.io/faq

**Comment by snowzach** [comment]
Going to close this, reopen if you still have issues.
