### ISSUE TITLE
ERROR - Could not create detector pytorch/pytorch: No module named 'IPython'

### ISSUE THREAD

**Issue by SuperJuke** [snowzach/doods2#60]
Tried Doods2 by running,

`docker run -it -p 8080:8080 snowzach/doods2:latest`

The container successfully ran but out of the 3 models, only 'default' and 'tensorflow' shows in the dropdown on the http://localhost:8080/. The pytorch(Yolo5s) is missing. The following error is seen in the logs:

> ERROR - Could not create detector pytorch/pytorch: No module named 'IPython'

**Comment by snowzach** [comment]
What hardware are you running on?

**Comment by SuperJuke** [comment]
AMD.

**Comment by snowzach** [comment]
And just the default config file?

**Comment by SuperJuke** [comment]
Yes.

**Comment by snowzach** [comment]
Ughhhh... The yolo guys changed something again.... It downloads their model from the torch hub and if they change something it breaks... I'll see if I can fix...

**Comment by SuperJuke** [comment]
Issue #56 and #63 and this one(#60) are basically reporting the same error. Seems to be an issue with the latest docker image.

**Comment by SuperJuke** [comment]
> Ughhhh... The yolo guys changed something again.... It downloads their model from the torch hub and if they change something it breaks... I'll see if I can fix...

Ok. Thanks for checking.

**Comment by snowzach** [comment]
Repull your image and try it now..

**Comment by SuperJuke** [comment]
The Pytorch detector is now available and working under the Web Interface ... and might I add it gives the most accurate results of the 3. Thank you.

**Comment by snowzach** [comment]
Great!
