### ISSUE TITLE
error while decoding MB

### ISSUE THREAD

**Issue by MarkStephan89** [snowzach/doods2#61]
Hi, 
sometimes (after hours) these error is shown: 

`[h264 @ 0x7fa5f4d5eb40] error while decoding MB 66 35, bytestream -11`

I read https://stackoverflow.com/questions/64464169/error-while-decoding-mb-171-1-bytestream-27 and think, that the camera has a single fault image....

Can you add the workaround to doods? (link) or do you have another idea?

Thanks for doods!

more infos: https://www.anycodings.com/1questions/2653121/opencv-read-errorh264-0x8f915e0-error-while-decoding-mb-53-20-bytestream-7

```
This problem is created when you use the captured frames in the further processing and you create a delay in the pipeline while the rtsp is still streaming.

The solution is to put the capture on a different thread and the frames you use on another thread.
```

But my python is very bad....

**Comment by snowzach** [comment]
Closing this... I am not sure how i would fix it. Whatever you are using may need to retry.
