### ISSUE TITLE
DOODS Container unable to start with edgeTPU included

### ISSUE THREAD

**Issue by tokenwizard** [snowzach/doods2#64]
Using the docker run command in the instructions, I was able to run the container and use the web interface. 

I then updated my configs for the Coral USB device and now I am getting this error:

4f4fb700ef54: Pull complete
c099e822da9e: Pull complete
Digest: sha256:e8e39ba734d0055e56c058d0b5e3953d691149baea7bd767a8fd003c95f34ebd
Status: Downloaded newer image for snowzach/doods2:amd64-gpu
Creating doods2_doods_1 ... done
Attaching to doods2_doods_1
doods_1  | The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
doods2_doods_1 exited with code 139

Here is my config.yaml (with the relevant entry for the edgeTPU at the bottom):

server:
  host: 0.0.0.0
  port: 8080
  metrics: true
logging:
  level: info
doods:
  log: detections
  boxes:
    enabled: True
    boxColor: [0, 255, 0]
    boxThickness: 1
    fontScale: 1.2
    fontColor: [0, 255, 0]
    fontThickness: 1
  regions:
    enabled: True
    boxColor: [255, 0, 255]
    boxThickness: 1
    fontScale: 1.2
    fontColor: [255, 0, 255]
    fontThickness: 1
  globals:
    enabled: True
    fontScale: 1.2
    fontColor: [255, 255, 0]
    fontThickness: 1
  detectors:
    - name: default
      type: tflite
      modelFile: models/coco_ssd_mobilenet_v1_1.0_quant.tflite
      labelFile: models/coco_labels0.txt
      hwAccel: false
      numThreads: 4
    - name: tensorflow
      type: tensorflow
      modelFile: models/faster_rcnn_inception_v2_coco_2018_01_28.pb
      labelFile: models/coco_labels1.txt
      hwAccel: false
    - name: edgeTPU
      type: tflite
      modelFile: models/ssd_mobilenet_v1_coco_quant_postprocess_edgetpu.tflite
      labelFile: models/coco_labels.txt
      hwAccel: true
      numThreads: 4

And here is my docker-compose.yaml with the edgeTPU USB bus device passed to the container:

version: '3.2'
services:
  doods:
    image: snowzach/doods2:amd64-gpu
    ports:
      - "8080:8080"
    devices:
      - /dev/bus/usb/007/002

**Comment by snowzach** [comment]
It's staying you don't have SSE4.1... What processor are you running this on?

**Comment by tokenwizard** [comment]
This is on an LXC on Proxmox on a Dell PowerEdge with dual Intel Xeon E5-2670 CPUs.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by snowzach** [comment]
Do you have a GPU attached to this? I would just use the `latest` image instead of the GPU image. The GPU image is designed for NVidia GPUs. Also, I would check the Proxmox settings. I don't think it's exposing all the capabilities of the chip.

**Comment by snowzach** [comment]
Actually the `amd64` tag would be the best to use for that processor.

**Comment by snowzach** [comment]
And the E5-2670 definitely supports SSE 4.1 so I'm not sure why it would print that message unless it's running in a VM or something. Not sure how Proxmox does LXC.

**Comment by tokenwizard** [comment]
Ok,
I'll fiddle with my Proxmox/LXC config a bit.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by tokenwizard** [comment]
Figured it out. I actually had ended up going with a VM in Proxmox because it was easier to passthrough the USB Coral device. 

Changing the CPU type to "host" seems to have resolved that error:
![image](https://user-images.githubusercontent.com/24832561/200341859-983cb211-cfce-4f73-b683-9354d584ac4f.png)

Now I have the web interface running and working, but the edgeTPUI detector is not configured. 

I added this entry to the bottom of the config.yaml and placed this in the same folder with the docker-compose.yaml and the "models" folder where I downloaded the tflite and labels files (the first two were there and are detected and available in the Web Interface):

  detectors:
    - name: default
      type: tflite
      modelFile: models/coco_ssd_mobilenet_v1_1.0_quant.tflite
      labelFile: models/coco_labels0.txt
      hwAccel: false
      numThreads: 4
    - name: tensorflow
      type: tensorflow
      modelFile: models/faster_rcnn_inception_v2_coco_2018_01_28.pb
      labelFile: models/coco_labels1.txt
      hwAccel: false
    - name: edgeTPU
      type: tflite
      modelFile: models/ssd_mobilenet_v1_coco_quant_postprocess_edgetpu.tflite
      labelFile: models/coco_labels.txt
      hwAccel: true
      numThreads: 4
