### ISSUE TITLE
Troubleshooting/Documenting EdgeTPU usage with DOODS2 running in a Proxmox LXC

### ISSUE THREAD

**Issue by tokenwizard** [snowzach/doods2#66]
Looking through the documentation in the README section, it seems like if you want to use edgeTPU, you need to create a docker-compose.yaml like the example provided so you can pass the device to the DOODS container. It also looks like you need to create a config.yaml to add the edgeTPU Detector.

There is mention that it will look for the config.yaml in the current working directory and if it does not see one it will use the built-in config in the image. Is that correct? 

I have this folder structure:

~/doods2$ ls -lah
total 20K
drwxr-xr-x 3 doods doods 4.0K Nov  7 10:50 .
drwxr-xr-x 4 doods doods 4.0K Nov  7 09:48 ..
-rw-r--r-- 1 doods doods 1.1K Nov  4 11:15 config.yaml
-rw-r--r-- 1 doods doods  144 Nov  7 09:52 docker-compose.yaml
drwxr-xr-x 2 doods doods 4.0K Nov  4 11:14 models

In my config.yaml, I have added a third detector called edgeTPU and it references the models folder for the model and labels.

  detectors:
    - name: default
      type: tflite
      modelFile: models/coco_ssd_mobilenet_v1_1.0_quant.tflite
      labelFile: models/coco_labels0.txt
      hwAccel: false
      numThreads: 4
    - name: tensorflow
      type: tensorflow
      modelFile: models/faster_rcnn_inception_v2_coco_2018_01_28.pb
      labelFile: models/coco_labels1.txt
      hwAccel: false
    - name: edgeTPU
      type: tflite
      modelFile: models/ssd_mobilenet_v1_coco_quant_postprocess_edgetpu.tflite
      labelFile: models/coco_labels.txt
      hwAccel: true
      numThreads: 4

And in my docker-compose.yaml, I have the USB device passed:

version: '3.2'
services:
  doods:
    image: snowzach/doods2:amd64-gpu
    ports:
      - "8080:8080"
    devices:
      - /dev/bus/usb/002/002

For some reason, I am only getting the two default detectors as options. I'm not sure if I'm missing a step that may not be documented, or if it is just ignoring my config.yaml and using the built-in one for some reason. 

![Screenshot_2022-11-07-14-31-21_2560x1080](https://user-images.githubusercontent.com/24832561/200398299-da4f4c81-4419-4397-a976-92ee4914fc36.png)

Any ideas? 

TIA!

**Comment by snowzach** [comment]
You need to pass in the config file and the models file to the docker container.  Try adding this to your docker compose file:
```
volumes:
  - ./models:/opt/doods/models
  - ./config.yaml:/opt/doods/config.yaml
```

**Comment by tokenwizard** [comment]
Ah,
I knew I was missing something simple. I'm a late bloomer with all this docker stuff.

------- Original Message -------

**Comment by tokenwizard** [comment]
Ok, I spun up a fresh LXC in Proxmox and confirmed my USB Coral device is showing up in the container. Per some guidance I found on Proxmox forums I added a udev rule to create a symlink for the coral device at /dev/CoralUSB. I then confirmed that the Coral device is working directly on the Proxmox server, and it is showing up inside the Proxmox LXC.

![image](https://user-images.githubusercontent.com/24832561/200941316-54f7e952-3f0c-4c1e-9f9a-e91a15635b44.png)

Then I added that USB device to my docker-compose.yaml and added the edgeTPU detector to my config.yaml (commented out the default and tensorflow ones since my models folder only includes the edgeTPU model and labels).

![image](https://user-images.githubusercontent.com/24832561/200941499-c9c9115a-ea8b-46d1-a4cb-05bb0d4ec6f9.png)

![image](https://user-images.githubusercontent.com/24832561/200941607-bd22bed8-2bfb-4515-afde-b2dbcff850dc.png)

I also added the config and models volumes to the docker-compose.yaml as you can see in the above screenshot. 

Are all the edgeTPU drivers/dependencies included in the DOODS2 container? Should this just work "out of the box" as long as the USB device is recognized on the device running the DOODS2 container? 

This is what I am getting when I start up the DOODS2 container:

**Comment by tokenwizard** [comment]
I can load the web GUI but there are no detectors configured, since the edgeTPU failed.

**Comment by snowzach** [comment]
There's something automatic the library uses to find the Coral... Its not likely looking for it at your udev alias.. Try using `/dev/bus/usb` instead.

**Comment by tokenwizard** [comment]
Ok, 
I updated my LXC config to pass the whole USB bus to the LXC container. 
![image](https://user-images.githubusercontent.com/24832561/201102230-b9a3c3a8-c1fb-4ff1-9c70-3e433dc05278.png)

Then I verified that I can use the Coral device in the LXC container, so I know the passthrough is working:
![image](https://user-images.githubusercontent.com/24832561/201102383-b9f395e0-219d-4eeb-8a0e-5bc1cdd29a8d.png)

Next, I updated my docker-compose.yaml to pass the USB Bus to the DOODS container:
![image](https://user-images.githubusercontent.com/24832561/201105661-71144f43-e9ab-419c-b815-927d53860338.png)

Now it is properly getting connected and working in DOODS.

**Comment by snowzach** [comment]
You're probably passing the wrong labels file. There's several coco labels files. Sadly you kinda just gotta try them out until it looks right.

**Comment by tokenwizard** [comment]
Ok, I downloaded the tflite and labels from the same model at the Coral website. I'll double-check.

------- Original Message -------

**Comment by tokenwizard** [comment]
I have tried using the edgeTPU model tflite file with the coco_labels.txt file from the link you include to download them from:
![image](https://user-images.githubusercontent.com/24832561/201156348-0136848d-e4b2-4270-9fa2-4d7c372ad8f1.png)

As well as the v2 for that model with the coco_labels.txt from the test_data of the edgeTPU github project (https://github.com/google-coral/edgetpu/tree/master/test_data)

But both are giving me a label of "bicycle" when I would expect "car."
![Screenshot_2022-11-10-11-37-53_2560x1080](https://user-images.githubusercontent.com/24832561/201156730-1511f4ba-26bd-4455-b6db-9bf934d27ac7.png)

**Comment by tokenwizard** [comment]
I posed this over in the edgeTPU project as well, thinking they may be able to point me in the right direction as far as the labels file. 

This is the reply I got, which makes sense, because looking at the list, the first three lines are:
person
bicycle
car

![image](https://user-images.githubusercontent.com/24832561/201162160-d5e0b6d2-bb17-4a2e-ac9a-440c7b473bd7.png)


If the index is off by 1 it would explain why it is returning bicycle when it should be car.  Was there a reason for starting at index: 1 for doods? Should there be a modified labels file for use with doods?

**Comment by tokenwizard** [comment]
Here is a link to the issue I posted on edgeTPU where they seem to indicate a possible fix. I have exec'd into the doods container I'm running and changed the label.py file to use "index: 0" and will test to verify if future labels are correct. 

https://github.com/google-coral/edgetpu/issues/681

**Comment by snowzach** [comment]
Sorry, side tracked on this one... 

Added a labels option called `labelsStartFromZero: true` and it will work off of index 0
