### ISSUE TITLE
Pytorch not available: "No module named git"

### ISSUE THREAD

**Issue by pevecyan** [snowzach/doods2#68]
Hey,
I have tried to run latest image on my NUC (amd64), and it seems that pytorch registering is failing because of missing git. 
I am attaching logs: 
`2022-11-19 10:09:01,373 - doods.doods - INFO - Registered detector type:tflite name:default`
`2022-11-19 10:09:04,072 - doods.doods - INFO - Registered detector type:tensorflow name:tensorflow`
`2022-11-19 10:09:06,574 - doods.doods - ERROR - Could not create detector pytorch/pytorch: No module named 'git'`
`2022-11-19 10:09:06,628 - uvicorn.error - INFO - Started server process [1]`

I checked the docker image and there is indeed missing apt install for git while it is present for arm.
Could this be added in next release?
Thank you!

**Comment by snowzach** [comment]
Git it another shot...
