### ISSUE TITLE
 Stream and MQTT mode unable to recover from stream errors

### ISSUE THREAD

**Issue by fusetak** [snowzach/doods2#74]
When using either the websocket based `/stream` API or MQTT mode doods2 is not able to recover from network or other issues with the stream that it is consuming. It seems like when these issues happen doods2 either crashes or gets stuck in an infinite loop in [`fresh_frame.py`](https://github.com/snowzach/doods2/blob/master/fresh_frame.py#L44). 

It seems like this can be fixed by changing the conditional in [`streamer.py`](https://github.com/snowzach/doods2/blob/master/streamer.py#L24) to detect an issue with the `FreshestFrame.read()` (ie: it returning no data) and then just re-creating the `VideoCapture` and `FreshestFrame` in order to re-establish the stream. I would happy to submit a PR to implement this idea if it seems like a good idea.

**Comment by snowzach** [comment]
That seems reasonable. If you're willing to try it, I will happily accept it.
