### ISSUE TITLE
General purpose scripts

### ISSUE THREAD

**Issue by ianustec** [snowzach/doods2#77]
Hello,
thanks for your project.

I would like to implement tflite in home assistant but in HA OS it is not possible. I use your integration to detect entities in images.

I wonder if it is possible to implement a general script and not just dedicated to image detection.
So it would be possible to use your integration with any DNN model and with any type of sensors

It would be the user to declare the model structure as input and output.

Doable?

**Comment by snowzach** [comment]
It's not really designed to do anything but images. you are feel free to fork the repo and make it do whatever you like.
