### ISSUE TITLE
Trouble getting yolov5s working

### ISSUE THREAD

**Issue by MoHf7f4** [snowzach/doods2#79]
In home assistant I added the plugin and it's worked great until I try to add yolov5s.  It starts, but no client seems to do anything.  Logs show nothing happening.

Please advise, and big thanks for this tool!

[yolov5s-int8.tflite.gz](https://github.com/snowzach/doods2/files/10528537/yolov5s-int8.tflite.gz)

**Comment by snowzach** [comment]
I tried playing with this model but I couldn't get it to detect anything... it seems to work but always returns:
```
 DetectResponse(id='manual', image=None, detections=[], error=None, duration=1188.209674321115)
```
