### ISSUE TITLE
Boxes color

### ISSUE THREAD

**Issue by herveaurel** [snowzach/doods2#80]
I love Doods2!

How to change the color of the frame, with HassOS?

THANKS !

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/64784541/226279709-3e55e16c-e58d-458b-a944-6085471eda68.png">

**Comment by snowzach** [comment]
Hass OS needs to have the repo updated to support the doods2 format. I hope to get to it someday.

**Comment by snowzach** [comment]
I actually did this a while ago and forgot to update it.
