### ISSUE TITLE
detection cat as a person

### ISSUE THREAD

**Issue by joebar38** [snowzach/doods2#81]
Hi,

I have DOODS2 on Home Assistant. My cat is detected as 99% person with tensorflow.

Here is my setup :

`  - platform: doods
    url: "http://xxx.xxx.xxx:xxxx"
    detector: tensorflow
    scan_interval: 10000
    source:
      - entity_id: camera.salon1_detection
      - entity_id: camera.salon2_detection
    file_out:
      - "/media/detections/verifications/{{ camera_entity.split('_')[0] }}/verifiee.jpg"
      - "/media/detections/verifications/{{ camera_entity.split('_')[0] }}/historique/{{ now().strftime('%Y%m%d') }}/{{ now().strftime('%H%M%S') }}.jpg"
    labels:
      - name: person
        confidence: 90`

Is there a solution to fix this problem?
Thanks !
![image](https://user-images.githubusercontent.com/100775090/230947273-14daab96-1090-44c9-be9d-8997da97143f.png)

**Comment by snowzach** [comment]
Not really... It's the model... You can try a different one...

**Comment by joebar38** [comment]
Ok thanks. Which model would you recommend me ?

**Comment by snowzach** [comment]
You can try just using the default one... It might be more accurate... The only other possibly solution is to get a different cat. :-)

**Comment by joebar38** [comment]
> You can try just using the default one... It might be more accurate... The only other possibly solution is to get a different cat. :-)

I have already tried default and tensorflow models, same problem :( 
I think I'm going to change my cat :)
