### ISSUE TITLE
yolov7

### ISSUE THREAD

**Issue by rgogada** [snowzach/doods2#86]
any plans to include yolov7? thanks.

**Comment by snowzach** [comment]
I almost got it working... I'm no pytorch expert... But using this for model file almost got it working `WongKinYiu/yolov7,yolov7`

**Comment by rgogada** [comment]
I really want to try this but if I pass config file like this, it is complaining about file not found.

docker-compose
`doods:
    container_name: doods
    image: snowzach/doods2:amd64
    environment:
      - TZ=Australia/Adelaide
      - CONFIG_FILE=/root/docker/doods/config.yaml
    restart: unless-stopped
    network_mode: cust_bridge
    ports:
      - 8140:8080`

config.yaml
`doods:
  detectors:
    - name: pytorch
      type: pytorch
      modelFile: WongKinYiu/yolov7,yolov7`

docker logs
`Traceback (most recent call last):
  File "main.py", line 75, in <module>
    main()
  File "main.py", line 43, in main
    with open(config_file, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/root/docker/doods/config.yaml'`

**Comment by rgogada** [comment]
> volumes:
>       - /root/docker/doods/config.yaml:/opt/doods/config.yaml

this is how I used to run the DOODS1. but surprisingly when I tried to run DOODS2 this way couple of months ago it didn't work. Anyway it now works. Thanks.
