### ISSUE TITLE
New DOODS2 image (1.1.4) failing

### ISSUE THREAD

**Issue by rgogada** [snowzach/doods2#88]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from api import API
  File "/opt/doods/api.py", line 1, in <module>
    import uvicorn
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/__init__.py", line 1, in <module>
    from uvicorn.config import Config
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/config.py", line 21, in <module>
    from asgiref.typing import ASGIApplication
  File "/usr/local/lib/python3.8/dist-packages/asgiref/typing.py", line 22, in <module>
    from typing_extensions import NotRequired
ImportError: cannot import name 'NotRequired' from 'typing_extensions' (/usr/local/lib/python3.8/dist-packages/typing_extensions.py)

**Comment by snowzach** [comment]
Can you tell me what architecture are you running and can you provide your config?

**Comment by OmarHeshamACS** [comment]
i also have the same error with amd procesor and on home assistant 2023.3.0 and supervisor 2023.04.1 and Operating System 9.5
![image](https://github.com/snowzach/doods2/assets/64424287/97e15227-a7ed-4726-b959-a84ccb5b5053)

**Comment by OmarHeshamACS** [comment]
> i also have the same error with amd procesor and on home assistant 2023.3.0 and supervisor 2023.04.1 and Operating System 9.5 ![image](https://user-images.githubusercontent.com/64424287/240630285-97e15227-a7ed-4726-b959-a84ccb5b5053.png)

![image](https://github.com/snowzach/doods2/assets/64424287/f0a66785-4287-4208-96d7-71dc86b41d40)

**Comment by snowzach** [comment]
Okay, building another now that will hopefully fix it...

**Comment by snowzach** [comment]
Make sure you pull the latest doods2 container. I just updated it.. Hopefully it fixes that issue.

**Comment by rgogada** [comment]
yeah, now it works. thanks for the fast response.

**Comment by rgogada** [comment]
you should include "buy me  a coffee/beer" thing. cheers.

**Comment by snowzach** [comment]
Ha ha.. Sure!
