### ISSUE TITLE
Error with creating detector pytorch

### ISSUE THREAD

**Issue by OmarHeshamACS** [snowzach/doods2#89]
I have an issue with creating pytorch model 
![image](https://github.com/snowzach/doods2/assets/64424287/a518c441-d9f8-459b-ba45-ff09bdd97411)

my configuration is 
![image](https://github.com/snowzach/doods2/assets/64424287/fdfe55b5-7c1d-4ef2-ac4c-73b3db418ec4)

**Comment by snowzach** [comment]
Try pulling the latest image and trying again. I hopefully just fixed that.

**Comment by snowzach** [comment]
Pretty sure this is fixed. Reopen if still broke after trying the latest image.
