### ISSUE TITLE
Request : having separate_detections and crop parameter available for curl too?

### ISSUE THREAD

**Issue by eravion** [snowzach/doods2#95]
Hello,

Could it be possible to have this parameter available for curl in addition to MQTT?
  "separate_detections" : false,
  "crop": false,
  
  In case we have multiple object, crop and copy each one to a folder with the category.

Thks

**Comment by snowzach** [comment]
It's not really possible to download multiple images in a single curl call unless you zipped them up or something which seems kind of painful.

**Comment by snowzach** [comment]
You could write a script to do this maybe... Send the image, get back all the detections as JSON and then parse out the detections into separate images. DOODS isn't going to do this bit. Closing ticket.
