### ISSUE TITLE
MQTT features

### ISSUE THREAD

**Issue by BrunoDurren** [snowzach/doods2#99]
Hi,

Could someone help me to understand if DOODS2 works with MQTT ? There's a mqtt.py file, but my knowledge in python is limited...
A documentation would be nice !
Thanks in advance...

**Comment by LuquinhasSG** [comment]
> Hi,
> 
> Could someone help me to understand if DOODS2 works with MQTT ? There's a mqtt.py file, but my knowledge in python is limited... A documentation would be nice ! Thanks in advance...

I would also like to know, so far I managed to set the mqtt configurations in the config.py file, but I don't know how to start, I'm looking at the project to understand, from what I understood you pass the "mqtt" argument when running doods, but as it is in a Docker container I'm trying to figure out where I can put this argument, the bad thing is that the feature exists, but there is no documentation...

**Comment by snowzach** [comment]
Yeah, I didn't create that feature I don't think... There's 2 modes, one where you can send requests over MQTT and another mode where you preconfigure the settings in the config file and it will continously run detections and stream the results over MQTT. If you are truly interested in using this, I will try to write up the docs in the next few days.

**Comment by LuquinhasSG** [comment]
> Yeah, I didn't create that feature I don't think... There's 2 modes, one where you can send requests over MQTT and another mode where you preconfigure the settings in the config file and it will continously run detections and stream the results over MQTT. If you are truly interested in using this, I will try to write up the docs in the next few days.

it would be nice!
![NiceTheRockGIF](https://github.com/snowzach/doods2/assets/55420795/770fdab3-cc0e-4edd-a3cd-f3b5f7702d7d)

**Comment by BrunoDurren** [comment]
@snowzach : It would be very nice indeed. I like DOODS for the ratio easy/performance an try to interact with a Jeedom server (challenger of HomeAssistant...)

**Comment by snowzach** [comment]
Okay, I added a blurb to the README about MQTT. Let me know if you have other questions.

**Comment by BrunoDurren** [comment]
Thank you, i will check that !
